### ISSUE TITLE
State of this crate?

### ISSUE THREAD

**Issue by Follpvosten** [antoyo/tql#36]
I would really like to use this crate for my projects, but I don't know enough about low-level rust or procedural macros to be able to fix or maintain it myself.

I really don't like Diesel's approach, so having an alternative like this one would be a great deal for me. So, I'd like to ask if there is any chance of tql getting maintained in the future? Maybe after proc macros stabilized? I would love to use it.

**Comment by antoyo** [comment]
To be honest, I don't really work on it anymore, so contributors would be welcome.
I would gladly help anyone to take over this project.

The proc macros are already stabilized as far as I know: this library only needs to be updated to work on stable.

As an additional note, I'm not sure the approach used in this library is the best one because that requires a lot of hacks in order to do the type-checking with only the syntax information. It did not required these hacks when it was a compiler plugin because we have access to types in compiler plugins.

**Comment by Ygg01** [comment]
> As an additional note, I'm not sure the approach used in this library is the best one because that requires a lot of hacks in order to do the type-checking with only the syntax information. It did not required these hacks when it was a compiler plugin because we have access to types in compiler plugins.

A question. Is there a way to keep this a compiler plugin in modern Rust?

**Comment by antoyo** [comment]
@Ygg01: Compiler plugins will never be stable.
The only hope is they add a proc-macro type that will given access to types, but I don't know if there are any plan to do so.

**Comment by antoyo** [comment]
Maybe `const fn` could now be used to remove hacks and/or improve error messages.

Anyway, I'm closing this issue. If anyone wants to maintain this crate, I'll be happy to help explain the code.

**Comment by ibraheemdev** [comment]
> I'm not sure the approach used in this library is the best one because that requires a lot of hacks in order to do the type-checking with only the syntax information.

@antoyo Could you point me to an example of a "hack" that is use to typecheck in the macro?

**Comment by antoyo** [comment]
@ibraheemdev: https://github.com/antoyo/tql/blob/43f7379f3e8a6e2555306aa934aee7799904264a/tql_macros/src/lib.rs#L524-L535

**Comment by ibraheemdev** [comment]
I was looking into this and I ran into a new crate called [butane](https://github.com/Electron100/butane). It basically generates methods for each column/field and uses a proc-macro to call those methods in a type safe manner. Unlike diesel, you do not have to import a `schema` because the methods are associated with each model:
```rust
let posts = query!(Post, published == true).limit(5).load(&conn)?;
```
I personally like tql's syntax much better, and I am going to start experimenting on combining these two methods to make tql type safe without "hacks".

**Comment by ibraheemdev** [comment]
Side note: Post fix macros would make this look a lot better: 
```rust
let posts = Post.filter!(published == true).limit(5).load(&conn)?;
```

**Comment by antoyo** [comment]
That's an idea that I deciced not to use in `tql` because the goal was to generate the SQL at compile-time (which comes with other limitations).

Butane looks cool: why not use it?
